---
- name: Create the node_exporter group
  group:
    name: "node_exporter"
    state: present
    system: true
  tags:
    - node_exporter
- name: Create the node_exporter user
  user:
    name: "node_exporter"
    groups: "node_exporter"
    append: true
    shell: /usr/sbin/nologin
    system: true
    create_home: false
    home: /
  tags:
    - node_exporter

- name: Download node_exporter binary to local folder
  become: false
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    mode: '0644'
  register: _download_binary
  until: _download_binary is succeeded
  retries: 5
  delay: 2
  delegate_to: localhost
  check_mode: false
  tags:
    - node_exporter

- name: Unpack node_exporter binary
  become: false
  unarchive:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: "/tmp"
    creates: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
  delegate_to: localhost
  check_mode: false
  tags:
    - node_exporter

- name: Propagate node_exporter binaries
  copy:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
    dest: "/usr/local/bin/node_exporter"
    mode: 0755
    owner: root
    group: root
  tags:
    - node_exporter

- name: Setting up the Node Exporter as a service
  copy:
    src: node_exporter.service
    dest: /etc/systemd/system/node_exporter.service
  tags:
    - node_exporter
- name: Start node exporter service
  systemd:
    name: node_exporter
    state: started
  tags:
    - node_exporter

