---
- name: pgsql-server
  hosts: pgsql
  become: true
  become_user: root
  become_method: sudo
  vars_files:
    - vars.yml

  pre_tasks:
    - name: Gather facts from ALL hosts (regardless of limit or tags)
      setup:
      delegate_to: "{{ item }}"
      delegate_facts: True
      when: hostvars[item]['ansible_default_ipv4'] is not defined
      with_items: "{{ groups['all'] }}"
      tags:
        - config

  tasks:
    - include: tasks/zookeeper.yml
    - include: tasks/postgresql.yml
    - include: tasks/patroni.yml
