---
- name: Install haproxy package
  package:
    name: haproxy
    state: present
  tags:
    - haproxy

- name: Get HAProxy version.
  command: haproxy -v
  register: haproxy_version_result
  changed_when: false
  check_mode: false
  tags:
    - haproxy

- name: generate HAProxy configuration .
  template:
    src: haproxy.cfg.j2
    dest: files/haproxy.cfg
    mode: 0644
    #validate: haproxy -f %s -c -q
  #notify: restart haproxy
  delegate_to: localhost
  tags:
    - haproxy 
- name: Copy HAProxy configuration in place.
  copy:
    src: files/haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
  tags:
    - haproxy
- name: restart haproxy
  service: 
    name: haproxy
    state: restarted
  tags:
    - haproxy
- name: Ensure HAProxy is started and enabled on boot.
  service: 
    name: haproxy
    state: started
    enabled: yes
  tags:
    - haproxy
